; T049: ABI table for powerpc64le-linux-gnu.

[properties]
bits_per_long       = 64
arith_right_shift   = 1
fma_policy          = auto
long_double         = target_native
x86_specializations = false
tune_table          = generic
exec_mode           = qemu-user
exe_wrapper         = qemu-ppc64le-static
shlib_style         = elf
threading           = pthread
tls_hack            = false
