"""Tune-artifact writer (FR-005c, contracts/tune-table-schema.md).

Writes the Wizard's output to `src/meson/tune-tables/host-tuned.ini`
(or wherever `--output` points), atomically, in INI format, with
[parameters] sorted by TunableParameter declaration order.
"""
from __future__ import annotations

import datetime as dt
import io
import os
import tempfile
from pathlib import Path
from typing import Mapping

from .parameters import PARAMETERS, PARAMETERS_BY_NAME, ValueType, ValueT


def _validate_parameters(parameters: Mapping[str, ValueT]) -> None:
    """Reject payloads that don't match the frozen parity list.

    Strict side: writer rejects unknown extras and type mismatches.
    Forward-compat (reader leniency on unknown extras) is implemented
    in `src/meson/read-tune-table.py`, NOT here.
    """
    known = set(PARAMETERS_BY_NAME)
    given = set(parameters)

    extras = given - known
    if extras:
        raise ValueError(
            f"Unknown parameter(s) for current Wizard version: {sorted(extras)}. "
            f"Update tools/ntl_wizard/parameters.py before emitting them."
        )

    missing = known - given
    if missing:
        raise ValueError(
            f"Missing required parameter(s): {sorted(missing)}. "
            f"Every TunableParameter in PARAMETERS must have a value."
        )

    # Per-parameter type / domain check
    for name, value in parameters.items():
        spec = PARAMETERS_BY_NAME[name]
        if spec.value_type is ValueType.BOOL_FLAG:
            if value not in (0, 1, True, False):
                raise TypeError(
                    f"{name}: bool_flag value must be 0 or 1; got {value!r}"
                )
        elif spec.value_type is ValueType.INT_THRESHOLD:
            if not isinstance(value, int) or isinstance(value, bool):
                raise TypeError(
                    f"{name}: int_threshold value must be a non-bool int; got {value!r}"
                )
            if value not in spec.value_domain:
                raise ValueError(
                    f"{name}: value {value!r} not in domain {spec.value_domain!r}"
                )
        elif spec.value_type is ValueType.CHOICE:
            if value not in spec.value_domain:
                raise ValueError(
                    f"{name}: choice {value!r} not in domain {spec.value_domain!r}"
                )


def _required_provenance_fields() -> tuple[str, ...]:
    return (
        "ntl_version",
        "wizard_version",
        "host_fingerprint",
        "host_cpu",
        "host_os",
        "compiler",
        "generated_utc",
        "session_id",
    )


def _validate_provenance(provenance: Mapping[str, str]) -> None:
    missing = set(_required_provenance_fields()) - set(provenance)
    if missing:
        raise ValueError(
            f"Provenance missing required fields: {sorted(missing)}"
        )


def write_artifact(
    path: Path,
    parameters: Mapping[str, ValueT],
    provenance: Mapping[str, str],
) -> None:
    """Atomically write the tune artifact INI to `path`.

    Writes go via tempfile + os.replace in the same directory, so an
    observer reading `path` always sees either no file, the previous
    valid file, or the new valid file — never a partial.
    """
    path = Path(path)
    _validate_parameters(parameters)
    _validate_provenance(provenance)

    # Render to an in-memory buffer first so we never partial-write.
    buf = io.StringIO()
    buf.write("; Generated by ntl-wizard. Do not edit by hand unless you\n")
    buf.write("; understand the NTL tune-parameter semantics. To regenerate:\n")
    buf.write(";    pip install <NTL-source>/tools && ntl-wizard\n")
    buf.write(f"; Generated {provenance['generated_utc']} on {provenance.get('host_cpu', 'unknown CPU')}.\n")
    buf.write("\n")
    buf.write("[parameters]\n")
    for p in PARAMETERS:  # declaration order, NOT alphabetical
        value = parameters[p.name]
        # Normalize booleans to 0/1 ints for INI rendering
        if isinstance(value, bool):
            value = int(value)
        buf.write(f"{p.name} = {value}\n")

    buf.write("\n[provenance]\n")
    for key in _required_provenance_fields():
        buf.write(f"{key} = {provenance[key]}\n")

    rendered = buf.getvalue()

    # Atomic write: tempfile in target dir, then os.replace.
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(
        prefix=path.name + ".",
        suffix=".tmp",
        dir=str(path.parent),
    )
    try:
        # Write the bytes with explicit LF (not OS-default).
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as f:
            f.write(rendered)
        os.replace(tmp_name, path)
    except Exception:
        # Best-effort cleanup of the tempfile.
        try:
            os.unlink(tmp_name)
        except OSError:
            pass
        raise


def now_utc_iso() -> str:
    """Helper for the Wizard / tests to produce a consistent
    generated_utc timestamp."""
    return dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
